/**
 * Math equation editor symbol palette.
 *
 * Mirrors Canvas LMS's palette inventory (canvas-rce/.../EquationEditorToolbar/buttons.js)
 * so that teachers migrating from Canvas see the same symbols and templates.
 *
 * Each entry has:
 *   command          — LaTeX inserted in WYSIWYG mode (with \placeholder{} for templates).
 *   advancedCommand  — LaTeX inserted in raw-LaTeX mode (no \placeholder, plain braces).
 *   displayName      — small LaTeX rendered as the button label (preferred when set).
 *   label            — human-readable description, used as aria-label and tooltip.
 */

const PLACEHOLDER = '\\placeholder{}';

/** Convenience helper for entries that are simple symbols (button shows the rendered LaTeX). */
const sym = (command, label) => ({ command, label });

/** Convenience helper for templates with a fillable display + raw fallback. */
const tmpl = (displayName, withPlaceholder, withoutPlaceholder, label) => ({
  command: withPlaceholder,
  advancedCommand: withoutPlaceholder,
  displayName,
  label,
});

export const PALETTE = [
  {
    name: 'Basic',
    commands: [
      tmpl('x_{⬚}', `_{${PLACEHOLDER}}`, '_{ }', 'Subscript'),
      tmpl('x^{⬚}', `^{${PLACEHOLDER}}`, '^{ }', 'Superscript'),
      tmpl('\\frac{⬚}{⬚}', `\\frac{${PLACEHOLDER}}{${PLACEHOLDER}}`, '\\frac{ }{ }', 'Fraction'),
      tmpl('\\sqrt{⬚}', `\\sqrt{${PLACEHOLDER}}`, '\\sqrt{ }', 'Square root'),
      tmpl('\\sqrt[n]{⬚}', `\\sqrt[${PLACEHOLDER}]{${PLACEHOLDER}}`, '\\sqrt[ ]{ }', 'N-th root'),
      sym('\\langle', 'Left angle bracket'),
      sym('\\rangle', 'Right angle bracket'),
      tmpl('\\binom{⬚}{⬚}', `\\binom{${PLACEHOLDER}}{${PLACEHOLDER}}`, '\\binom{ }{ }', 'Binomial coefficient'),
      sym('f', 'F (function)'),
      sym('\\prime', 'Prime'),
      sym('+', 'Plus'),
      sym('-', 'Minus'),
      sym('\\pm', 'Plus / minus'),
      sym('\\mp', 'Minus / plus'),
      sym('\\cdot', 'Centered dot'),
      sym('=', 'Equals sign'),
      sym('\\times', 'Multiplication sign'),
      sym('\\div', 'Division sign'),
      sym('\\ast', 'Asterisk'),
      sym('\\therefore', 'Therefore'),
      sym('\\because', 'Because'),
      tmpl('\\sum_{⬚}^{⬚}', `\\sum_{${PLACEHOLDER}}^{${PLACEHOLDER}}`, '\\sum_{ }^{ }', 'Sum'),
      tmpl('\\prod_{⬚}^{⬚}', `\\prod_{${PLACEHOLDER}}^{${PLACEHOLDER}}`, '\\prod_{ }^{ }', 'Product'),
      tmpl('\\coprod_{⬚}^{⬚}', `\\coprod_{${PLACEHOLDER}}^{${PLACEHOLDER}}`, '\\coprod_{ }^{ }', 'Coproduct'),
      tmpl('\\int_{⬚}^{⬚}', `\\int_{${PLACEHOLDER}}^{${PLACEHOLDER}}`, '\\int_{ }^{ }', 'Definite integral'),
      sym('\\int', 'Indefinite integral'),
      sym('\\mathbb{N}', 'Natural numbers'),
      sym('\\mathbb{P}', 'Prime numbers'),
      sym('\\mathbb{Z}', 'Integers'),
      sym('\\mathbb{Q}', 'Rational numbers'),
      sym('\\mathbb{R}', 'Real numbers'),
      sym('\\mathbb{C}', 'Complex numbers'),
      sym('\\mathbb{H}', 'Quaternions'),
      tmpl('\\overline{⬚}', `\\overline{${PLACEHOLDER}}`, '\\overline{ }', 'Bar (overline)'),
      tmpl('\\hat{⬚}', `\\hat{${PLACEHOLDER}}`, '\\hat{ }', 'Hat'),
      tmpl('\\vec{⬚}', `\\vec{${PLACEHOLDER}}`, '\\vec{ }', 'Vector'),
    ],
  },

  {
    name: 'Greek',
    commands: [
      sym('\\alpha', 'Alpha'),
      sym('\\beta', 'Beta'),
      sym('\\gamma', 'Gamma'),
      sym('\\delta', 'Delta'),
      sym('\\epsilon', 'Epsilon'),
      sym('\\zeta', 'Zeta'),
      sym('\\eta', 'Eta'),
      sym('\\theta', 'Theta'),
      sym('\\iota', 'Iota'),
      sym('\\kappa', 'Kappa'),
      sym('\\lambda', 'Lambda'),
      sym('\\mu', 'Mu'),
      sym('\\nu', 'Nu'),
      sym('\\xi', 'Xi'),
      sym('\\pi', 'Pi'),
      sym('\\rho', 'Rho'),
      sym('\\sigma', 'Sigma'),
      sym('\\tau', 'Tau'),
      sym('\\upsilon', 'Upsilon'),
      sym('\\phi', 'Phi'),
      sym('\\chi', 'Chi'),
      sym('\\psi', 'Psi'),
      sym('\\omega', 'Omega'),
      sym('\\digamma', 'Digamma'),
      sym('\\varepsilon', 'Epsilon (variant)'),
      sym('\\vartheta', 'Theta (variant)'),
      sym('\\varkappa', 'Kappa (variant)'),
      sym('\\varpi', 'Pi (variant)'),
      sym('\\varrho', 'Rho (variant)'),
      sym('\\varsigma', 'Sigma (variant)'),
      sym('\\varphi', 'Phi (variant)'),
      sym('\\Gamma', 'Uppercase Gamma'),
      sym('\\Delta', 'Uppercase Delta'),
      sym('\\Theta', 'Uppercase Theta'),
      sym('\\Lambda', 'Uppercase Lambda'),
      sym('\\Xi', 'Uppercase Xi'),
      sym('\\Pi', 'Uppercase Pi'),
      sym('\\Sigma', 'Uppercase Sigma'),
      sym('\\Upsilon', 'Uppercase Upsilon'),
      sym('\\Phi', 'Uppercase Phi'),
      sym('\\Psi', 'Uppercase Psi'),
      sym('\\Omega', 'Uppercase Omega'),
    ],
  },

  {
    name: 'Operators',
    commands: [
      sym('\\wedge', 'And (wedge)'),
      sym('\\vee', 'Or (vee)'),
      sym('\\cup', 'Union'),
      sym('\\cap', 'Intersection'),
      sym('\\diamond', 'Diamond'),
      sym('\\bigtriangleup', 'Upward-pointing triangle'),
      sym('\\ominus', 'Encircled minus'),
      sym('\\uplus', 'Disjoint union'),
      sym('\\otimes', 'Encircled times'),
      sym('\\oplus', 'Encircled plus'),
      sym('\\bigtriangledown', 'Downward-pointing triangle'),
      sym('\\sqcap', 'Square cap'),
      sym('\\triangleleft', 'Leftward-pointing triangle'),
      sym('\\sqcup', 'Square cup'),
      sym('\\triangleright', 'Rightward-pointing triangle'),
      sym('\\odot', 'Encircled dot'),
      sym('\\bigcirc', 'Big circle'),
      sym('\\dagger', 'Dagger'),
      sym('\\ddagger', 'Double dagger'),
      sym('\\wr', 'Wreath product'),
      sym('\\amalg', 'Amalg (coproduct)'),
    ],
  },

  {
    name: 'Relationships',
    commands: [
      sym('<', 'Less than'),
      sym('>', 'Greater than'),
      sym('\\equiv', 'Equivalent (identity)'),
      sym('\\cong', 'Congruent'),
      sym('\\sim', 'Equivalence class'),
      sym('\\notin', 'Not in (not an element of)'),
      sym('\\ne', 'Not equal'),
      sym('\\propto', 'Proportional'),
      sym('\\approx', 'Approximately'),
      sym('\\le', 'Less than or equal'),
      sym('\\ge', 'Greater than or equal'),
      sym('\\in', 'In (element of)'),
      sym('\\ni', 'Contains'),
      sym('\\subset', 'Subset (strict)'),
      sym('\\supset', 'Superset (strict)'),
      sym('\\not\\subset', 'Not subset (strict)'),
      sym('\\not\\supset', 'Not superset (strict)'),
      sym('\\subseteq', 'Subset'),
      sym('\\supseteq', 'Superset'),
      sym('\\not\\subseteq', 'Not subset'),
      sym('\\not\\supseteq', 'Not superset'),
      sym('\\models', 'Inference'),
      sym('\\prec', 'Precedes'),
      sym('\\succ', 'Succeeds'),
      sym('\\preceq', 'Precedes or equal'),
      sym('\\succeq', 'Succeeds or equal'),
      sym('\\simeq', 'Group isomorphism'),
      sym('\\mid', 'Vertical bar (set builder)'),
      sym('\\ll', 'Much less than'),
      sym('\\gg', 'Much greater than'),
      sym('\\parallel', 'Parallel'),
      sym('\\bowtie', 'Bowtie'),
      sym('\\sqsubset', 'Square subset (strict)'),
      sym('\\sqsupset', 'Square superset (strict)'),
      sym('\\smile', 'Smile (cup product)'),
      sym('\\sqsubseteq', 'Square subset'),
      sym('\\sqsupseteq', 'Square superset'),
      sym('\\doteq', 'Approaches the limit'),
      sym('\\frown', 'Frown (cap product)'),
      sym('\\vdash', 'Turnstile (yields)'),
      sym('\\dashv', 'Reverse turnstile (does not yield)'),
      sym('\\exists', 'Exists'),
      sym('\\varnothing', 'Empty set'),
    ],
  },

  {
    name: 'Arrows',
    commands: [
      sym('\\longleftarrow', 'Long left arrow'),
      sym('\\longrightarrow', 'Long right arrow'),
      sym('\\Longleftarrow', 'Thick long left arrow'),
      sym('\\Longrightarrow', 'Thick long right arrow'),
      sym('\\longleftrightarrow', 'Logical equivalence'),
      sym('\\updownarrow', 'Up and down arrow'),
      sym('\\Longleftrightarrow', 'Logical equivalence (thick)'),
      sym('\\Updownarrow', 'Up and down arrow (thick)'),
      sym('\\mapsto', 'Maps to'),
      sym('\\nearrow', 'Up-and-right diagonal arrow'),
      sym('\\hookleftarrow', 'Left arrow with hook'),
      sym('\\hookrightarrow', 'Right arrow with hook'),
      sym('\\searrow', 'Down-and-right diagonal arrow'),
      sym('\\leftharpoonup', 'Left upward harpoon'),
      sym('\\rightharpoonup', 'Right upward harpoon'),
      sym('\\swarrow', 'Down-and-left diagonal arrow'),
      sym('\\leftharpoondown', 'Left downward harpoon'),
      sym('\\rightharpoondown', 'Right downward harpoon'),
      sym('\\nwarrow', 'Up-and-left diagonal arrow'),
      sym('\\downarrow', 'Down arrow'),
      sym('\\Downarrow', 'Thick down arrow'),
      sym('\\uparrow', 'Up arrow'),
      sym('\\Uparrow', 'Thick up arrow'),
      sym('\\rightarrow', 'Right arrow'),
      sym('\\Rightarrow', 'Thick right arrow'),
      sym('\\leftarrow', 'Left arrow'),
      sym('\\Leftarrow', 'Thick left arrow'),
      sym('\\leftrightarrow', 'Left and right arrow'),
      sym('\\Leftrightarrow', 'Thick left and right arrow'),
      sym('\\rightleftharpoons', 'Equilibrium'),
    ],
  },

  {
    name: 'Delimiters',
    commands: [
      sym('\\lfloor', 'Left floor'),
      sym('\\rfloor', 'Right floor'),
      sym('\\lceil', 'Left ceiling'),
      sym('\\rceil', 'Right ceiling'),
      sym('/', 'Forward slash'),
      sym('\\lbrace', 'Left curly brace'),
      sym('\\rbrace', 'Right curly brace'),
    ],
  },

  {
    name: 'Misc',
    commands: [
      sym('\\forall', 'For all'),
      sym('\\ldots', 'Low horizontal dots'),
      sym('\\cdots', 'Centered horizontal dots'),
      sym('\\vdots', 'Vertical dots'),
      sym('\\ddots', 'Diagonal dots'),
      sym('\\surd', 'Square root symbol'),
      sym('\\triangle', 'Triangle'),
      sym('\\ell', 'Script L'),
      sym('\\top', 'Top'),
      sym('\\flat', 'Flat (music)'),
      sym('\\natural', 'Natural (music)'),
      sym('\\sharp', 'Sharp (music)'),
      sym('\\wp', 'Power set'),
      sym('\\bot', 'Bottom'),
      sym('\\clubsuit', 'Clubs (suit)'),
      sym('\\diamondsuit', 'Diamonds (suit)'),
      sym('\\heartsuit', 'Hearts (suit)'),
      sym('\\spadesuit', 'Spades (suit)'),
      sym('\\backslash', 'Backslash'),
      sym('\\vert', 'Vertical bar'),
      sym('\\perp', 'Perpendicular'),
      sym('\\nabla', 'Nabla'),
      sym('\\hbar', 'H bar'),
      sym('\\circ', 'Open circle'),
      sym('\\bullet', 'Solid circle'),
      sym('\\setminus', 'Set minus'),
      sym('\\neg', 'Not (negation)'),
      sym('\\Re', 'Real part'),
      sym('\\Im', 'Imaginary part'),
      sym('\\partial', 'Partial derivative'),
      sym('\\infty', 'Infinity'),
      sym('\\aleph', 'Aleph'),
      sym('^\\circ', 'Degree symbol'),
      sym('\\angle', 'Angle'),
    ],
  },
];

/**
 * Patterns Canvas's WYSIWYG (mathlive) cannot render — when present in existing
 * LaTeX, force the modal into Advanced (raw textarea) mode so the user can edit
 * the source. Mirrors canvas-rce/.../advancedOnlySyntax.js.
 */
export const ADVANCED_ONLY_PATTERNS = [
  /\\text\b/,
  /\\mbox\b/,
  /\\newcommand\b/,
  /\\def\b/,
  /\\bbox\b/,
  /\\newline\b/,
  /\\\\/,
];

export const requiresAdvancedMode = (latex) =>
  !!latex && ADVANCED_ONLY_PATTERNS.some((re) => re.test(latex));
