// genschema generates the initial migration SQL from the current GORM schema.
//
// It connects to the database, runs AutoMigrate, then dumps CREATE TABLE
// statements by querying information_schema and pg_catalog.
//
// Usage:
//
//	DATABASE_URL=postgres://... go run ./cmd/genschema > internal/db/migrations/000001_init.up.sql
package main

import (
	"database/sql"
	"fmt"
	"log"
	"strings"

	"github.com/joho/godotenv"
	"github.com/kocherm/paper-lms/internal/config"
	"github.com/kocherm/paper-lms/internal/db"
)

func main() {
	_ = godotenv.Load()
	cfg := config.Load()

	database, err := db.Connect(cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("Failed to connect: %v", err)
	}

	if err := db.AutoMigrate(database); err != nil {
		log.Fatalf("AutoMigrate failed: %v", err)
	}

	sqlDB, err := database.DB()
	if err != nil {
		log.Fatalf("Failed to get sql.DB: %v", err)
	}

	tables, err := getTables(sqlDB)
	if err != nil {
		log.Fatalf("Failed to get tables: %v", err)
	}

	fmt.Println("-- Paper LMS: Initial schema migration")
	fmt.Println("-- Generated by cmd/genschema from GORM AutoMigrate")
	fmt.Println("-- DO NOT EDIT — future changes should be new migration files")
	fmt.Println()

	for _, table := range tables {
		ddl, err := generateCreateTable(sqlDB, table)
		if err != nil {
			log.Fatalf("Failed to generate DDL for %s: %v", table, err)
		}
		fmt.Println(ddl)
		fmt.Println()
	}

	indexes, err := getIndexes(sqlDB)
	if err != nil {
		log.Fatalf("Failed to get indexes: %v", err)
	}
	if len(indexes) > 0 {
		fmt.Println("-- Indexes")
		for _, idx := range indexes {
			fmt.Printf("%s;\n", idx)
		}
	}
}

func getTables(db *sql.DB) ([]string, error) {
	rows, err := db.Query(`
		SELECT table_name FROM information_schema.tables
		WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
		AND table_name != 'schema_migrations'
		ORDER BY table_name
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var tables []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		tables = append(tables, name)
	}
	return tables, nil
}

func generateCreateTable(db *sql.DB, table string) (string, error) {
	// Get columns
	colRows, err := db.Query(`
		SELECT column_name, data_type, udt_name, character_maximum_length,
			   numeric_precision, numeric_scale, is_nullable, column_default
		FROM information_schema.columns
		WHERE table_schema = 'public' AND table_name = $1
		ORDER BY ordinal_position
	`, table)
	if err != nil {
		return "", err
	}
	defer colRows.Close()

	var cols []string
	for colRows.Next() {
		var colName, dataType, udtName, isNullable string
		var charMaxLen, numPrecision, numScale sql.NullInt64
		var colDefault sql.NullString

		if err := colRows.Scan(&colName, &dataType, &udtName, &charMaxLen, &numPrecision, &numScale, &isNullable, &colDefault); err != nil {
			return "", err
		}

		typeName := resolveType(dataType, udtName, charMaxLen, numPrecision, numScale)
		col := fmt.Sprintf("    %s %s", colName, typeName)
		if isNullable == "NO" {
			col += " NOT NULL"
		}
		if colDefault.Valid {
			col += fmt.Sprintf(" DEFAULT %s", colDefault.String)
		}
		cols = append(cols, col)
	}

	// Get primary key
	pkRows, err := db.Query(`
		SELECT kcu.column_name
		FROM information_schema.table_constraints tc
		JOIN information_schema.key_column_usage kcu
		  ON tc.constraint_name = kcu.constraint_name
		WHERE tc.table_schema = 'public' AND tc.table_name = $1
		AND tc.constraint_type = 'PRIMARY KEY'
		ORDER BY kcu.ordinal_position
	`, table)
	if err != nil {
		return "", err
	}
	defer pkRows.Close()

	var pkCols []string
	for pkRows.Next() {
		var col string
		if err := pkRows.Scan(&col); err != nil {
			return "", err
		}
		pkCols = append(pkCols, col)
	}
	if len(pkCols) > 0 {
		cols = append(cols, fmt.Sprintf("    PRIMARY KEY (%s)", strings.Join(pkCols, ", ")))
	}

	// Get unique constraints
	ucRows, err := db.Query(`
		SELECT tc.constraint_name, kcu.column_name
		FROM information_schema.table_constraints tc
		JOIN information_schema.key_column_usage kcu
		  ON tc.constraint_name = kcu.constraint_name
		WHERE tc.table_schema = 'public' AND tc.table_name = $1
		AND tc.constraint_type = 'UNIQUE'
		ORDER BY tc.constraint_name, kcu.ordinal_position
	`, table)
	if err != nil {
		return "", err
	}
	defer ucRows.Close()

	uniqueConstraints := make(map[string][]string)
	for ucRows.Next() {
		var cName, col string
		if err := ucRows.Scan(&cName, &col); err != nil {
			return "", err
		}
		uniqueConstraints[cName] = append(uniqueConstraints[cName], col)
	}
	for name, ucCols := range uniqueConstraints {
		cols = append(cols, fmt.Sprintf("    CONSTRAINT %s UNIQUE (%s)", name, strings.Join(ucCols, ", ")))
	}

	return fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n%s\n);", table, strings.Join(cols, ",\n")), nil
}

func resolveType(dataType, udtName string, charMaxLen, numPrecision, numScale sql.NullInt64) string {
	switch dataType {
	case "character varying":
		if charMaxLen.Valid {
			return fmt.Sprintf("varchar(%d)", charMaxLen.Int64)
		}
		return "text"
	case "character":
		if charMaxLen.Valid {
			return fmt.Sprintf("char(%d)", charMaxLen.Int64)
		}
		return "char(1)"
	case "numeric":
		if numPrecision.Valid && numScale.Valid {
			return fmt.Sprintf("numeric(%d,%d)", numPrecision.Int64, numScale.Int64)
		}
		return "numeric"
	case "integer":
		return "integer"
	case "bigint":
		return "bigint"
	case "smallint":
		return "smallint"
	case "boolean":
		return "boolean"
	case "text":
		return "text"
	case "timestamp with time zone":
		return "timestamptz"
	case "timestamp without time zone":
		return "timestamp"
	case "date":
		return "date"
	case "double precision":
		return "double precision"
	case "real":
		return "real"
	case "bytea":
		return "bytea"
	case "jsonb":
		return "jsonb"
	case "json":
		return "json"
	case "uuid":
		return "uuid"
	case "USER-DEFINED":
		return udtName
	case "ARRAY":
		return udtName
	default:
		return dataType
	}
}

func getIndexes(db *sql.DB) ([]string, error) {
	rows, err := db.Query(`
		SELECT indexdef FROM pg_indexes
		WHERE schemaname = 'public'
		AND indexname NOT LIKE '%_pkey'
		AND tablename != 'schema_migrations'
		ORDER BY tablename, indexname
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var indexes []string
	for rows.Next() {
		var def string
		if err := rows.Scan(&def); err != nil {
			return nil, err
		}
		// Convert CREATE INDEX to CREATE INDEX IF NOT EXISTS
		def = strings.Replace(def, "CREATE INDEX ", "CREATE INDEX IF NOT EXISTS ", 1)
		def = strings.Replace(def, "CREATE UNIQUE INDEX ", "CREATE UNIQUE INDEX IF NOT EXISTS ", 1)
		indexes = append(indexes, def)
	}
	return indexes, nil
}
